services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - "${NEXTCLOUD_PORT}:80"
    volumes:
      - ${NEXTCLOUD_DATA_DIR}:/var/www/html
      - ${NEXTCLOUD_EXTERNAL_DIR}:/data
    networks:
      - nextcloud-net
    restart: always
    depends_on:
      - nextcloud-db

  nextcloud-db:
    image: postgres
    container_name: nextcloud-db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}

    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    networks:
      - nextcloud-net
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"

networks:
  nextcloud-net:
    driver: bridge
